export { AuthManager, Role, Schema, AuthError } from './lib';
export type {
  AllKeys,
  AuthorizeConstructOptions,
  AuthorizeRoleOptions,
  DefaultScope,
  IAuthManager,
  IPermission,
  IRole,
  ISchema,
  InferPermissions,
  InferResources,
  MergePermissions,
  RoleAddResult,
  RoleRemoveResult,
  RoleUpdateResult,
  Roles,
  TAuthPermissions,
  TAuthResources,
  TAutorizeOptions,
  TRoleOptions,
  ToJSONResult,
  ToObjectResult,
  addOptions,
  permission,
  permissions,
  removeOptions,
  scopes,
  updateOptions
} from './lib';
