export { AuthError, AuthManager, Role, Schema } from './lib';
export type {
  Actions,
  AllKeys,
  AuthErrorCodes,
  AuthorizeConstructOptions,
  AuthorizeRoleOptions,
  BasePermissions,
  DefaultScope,
  GetRoleConfig,
  IAuthManager,
  IPermission,
  IRole,
  InferPermissions,
  InferResources,
  IntersectionToUnion,
  MergePermissions,
  Resources,
  RoleAddResult,
  RoleRemoveResult,
  RoleUpdateResult,
  Roles,
  TAuthPermissions,
  TAuthResources,
  TAutorizeOptions,
  TRoleOptions,
  ToJSONResult,
  ToObjectResult,
  TransformedRole,
  addOptions,
  permission,
  permissions,
  removeOptions,
  updateOptions
} from './lib';
